<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Sieg.DocumentosFiscais.Aplicacao\Sieg.DocumentosFiscais.Aplicacao.csproj" />
    <ProjectReference Include="..\Sieg.DocumentosFiscais.Infraestrutura\Sieg.DocumentosFiscais.Infraestrutura.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
