<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1707;CA1806</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sieg.DocumentosFiscais.Aplicacao\Sieg.DocumentosFiscais.Aplicacao.csproj" />
    <ProjectReference Include="..\..\src\Sieg.DocumentosFiscais.Dominio\Sieg.DocumentosFiscais.Dominio.csproj" />
    <ProjectReference Include="..\..\src\Sieg.DocumentosFiscais.Infraestrutura\Sieg.DocumentosFiscais.Infraestrutura.csproj" />
  </ItemGroup>
</Project>
