// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sieg.DocumentosFiscais.Infraestrutura.Persistencia.Contexto;

#nullable disable

namespace Sieg.DocumentosFiscais.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(DocumentosFiscaisDbContext))]
    [Migration("20261001173602_CriarEstruturaInicial")]
    partial class CriarEstruturaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sieg.DocumentosFiscais.Dominio.Entidades.DocumentoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("ChaveFiscal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chave_fiscal");

                    b.Property<string>("CnpjDestinatario")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj_destinatario");

                    b.Property<string>("CnpjEmitente")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj_emitente");

                    b.Property<string>("ConteudoXml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo_xml");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset?>("DataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao");

                    b.Property<string>("HashConteudo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash_conteudo")
                        .IsFixedLength();

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<string>("UnidadeFederativa")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("unidade_federativa");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CnpjDestinatario")
                        .HasDatabaseName("ix_documentos_fiscais_cnpj_destinatario");

                    b.HasIndex("CnpjEmitente")
                        .HasDatabaseName("ix_documentos_fiscais_cnpj_emitente");

                    b.HasIndex("DataEmissao")
                        .HasDatabaseName("ix_documentos_fiscais_data_emissao");

                    b.HasIndex("HashConteudo")
                        .IsUnique()
                        .HasDatabaseName("ux_documentos_fiscais_hash_conteudo");

                    b.HasIndex("UnidadeFederativa")
                        .HasDatabaseName("ix_documentos_fiscais_unidade_federativa");

                    b.HasIndex("Tipo", "ChaveFiscal")
                        .IsUnique()
                        .HasDatabaseName("ux_documentos_fiscais_tipo_chave_fiscal")
                        .HasFilter("chave_fiscal IS NOT NULL");

                    b.ToTable("documentos_fiscais", (string)null);
                });

            modelBuilder.Entity("Sieg.DocumentosFiscais.Dominio.Entidades.EventoConsumido", b =>
                {
                    b.Property<Guid>("IdEvento")
                        .HasColumnType("uuid")
                        .HasColumnName("id_evento");

                    b.Property<string>("Consumidor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumidor");

                    b.Property<DateTimeOffset>("ConsumidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumido_em");

                    b.HasKey("IdEvento", "Consumidor");

                    b.ToTable("eventos_consumidos", (string)null);
                });

            modelBuilder.Entity("Sieg.DocumentosFiscais.Dominio.Entidades.EventoPendente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa_em");

                    b.Property<DateTimeOffset?>("PublicadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_em");

                    b.Property<int>("QuantidadeTentativas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_tentativas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tipo");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ultimo_erro");

                    b.HasKey("Id");

                    b.HasIndex("PublicadoEm", "ProximaTentativaEm")
                        .HasDatabaseName("ix_eventos_pendentes_publicacao");

                    b.ToTable("eventos_pendentes", (string)null);
                });

            modelBuilder.Entity("Sieg.DocumentosFiscais.Dominio.Entidades.ResumoDocumentoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("DocumentoFiscalId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_fiscal_id");

                    b.Property<DateTimeOffset>("GeradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gerado_em");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoFiscalId")
                        .IsUnique()
                        .HasDatabaseName("ux_resumos_documentos_fiscais_documento");

                    b.ToTable("resumos_documentos_fiscais", (string)null);
                });

            modelBuilder.Entity("Sieg.DocumentosFiscais.Dominio.Entidades.ResumoDocumentoFiscal", b =>
                {
                    b.HasOne("Sieg.DocumentosFiscais.Dominio.Entidades.DocumentoFiscal", null)
                        .WithOne()
                        .HasForeignKey("Sieg.DocumentosFiscais.Dominio.Entidades.ResumoDocumentoFiscal", "DocumentoFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
